In [28]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [29]:
df = pd.read_csv("C:\\ML_work\\Datasets\\Netflix_Recommodation\\Netflix_Recommodation.csv")

In [30]:
df.tail(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [31]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [32]:
# Removing show_id and date_added columns because this is not usefull for recommodation serch
df = df.drop(['show_id','date_added'],axis=1)

In [33]:
# checing nan values 
df.isna().sum()

type               0
title              0
director        2634
cast             825
country          831
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [34]:
df[df['duration'].isnull()]

,type,title,director,cast,country,release_year,rating,duration,listed_in,description
5541,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [35]:
df['duration'].unique()[:10]

array(['90 min', '2 Seasons', '1 Season', '91 min', '125 min',
       '9 Seasons', '104 min', '127 min', '4 Seasons', '67 min'],
      dtype=object)

In [36]:
# fill na with 0 min
df['duration'] = df['duration'].fillna(df['rating'])

# Movie duration (minutes)
df['Movie_Duration'] = df['duration'].apply(
    lambda x: int(x.split()[0]) if 'min' in x else 0
)

# TV show seasons
df['Seasons'] = df['duration'].apply(
    lambda x: int(x.split()[0]) if 'Season' in x else 0
)

df = df.drop('duration',axis=1)

In [37]:
df[df['rating'].isnull()][:]

,type,title,director,cast,country,release_year,rating,listed_in,description,Movie_Duration,Seasons
5989,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,2017,NaN,Movies,Oprah Winfrey sits down with director Ava DuVe...,37,0
6827,TV Show,Gargantia on the Verdurous Planet,NaN,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,2013,NaN,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel...",0,1
7312,TV Show,Little Lunch,NaN,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,2015,NaN,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take...",0,1
7537,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,2015,NaN,Dramas,"Amid the chaos and horror of World War II, a c...",115,0

In [38]:
df['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

In [39]:
df['rating']=df['rating'].apply(lambda x: np.nan if isinstance(x, str) and 'min' in x.split() else x)

In [40]:
df['rating'].unique()
df['rating'].isna().sum()

np.int64(7)

In [41]:
df['type'].unique()   #array(['Movie', 'TV Show'], dtype=object)

array(['Movie', 'TV Show'], dtype=object)

In [42]:
df.tail(3)

,type,title,director,cast,country,release_year,rating,listed_in,description,Movie_Duration,Seasons
8804,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2009,R,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,88,0
8805,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2006,PG,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",88,0
8806,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2015,TV-14,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,111,0

In [44]:
df['tags'] = (
    df['type'].fillna('') + ' ' +
    df['country'].fillna('') + ' ' +
    df['director'].fillna('') + ' ' +
    df['cast'].fillna('') + ' ' +
    df['listed_in'].fillna('') + ' ' +
    df['release_year'].fillna(0).astype(int).astype(str) + ' ' +
    df['description'].fillna('')
)

df = df[['tags','title']]

In [45]:
df

                                                   tags                  title
0     Movie United States Kirsten Johnson  Documenta...   Dick Johnson Is Dead
1     TV Show South Africa  Ama Qamata, Khosi Ngema,...          Blood & Water
2     TV Show  Julien Leclercq Sami Bouajila, Tracy ...              Ganglands
3     TV Show    Docuseries, Reality TV 2021 Feuds, ...  Jailbirds New Orleans
4     TV Show India  Mayur More, Jitendra Kumar, Ran...           Kota Factory
...                                                 ...                    ...
8802  Movie United States David Fincher Mark Ruffalo...                 Zodiac
8803  TV Show    Kids' TV, Korean TV Shows, TV Comed...            Zombie Dumb
8804  Movie United States Ruben Fleischer Jesse Eise...             Zombieland
8805  Movie United States Peter Hewitt Tim Allen, Co...                   Zoom
8806  Movie India Mozez Singh Vicky Kaushal, Sarah-J...                 Zubaan

[8807 rows x 2 columns]

In [46]:
df.isna().sum()

tags     0
title    0
dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['tags'])
vectorizer.get_feature_names_out()
print(X.shape)

(8807, 50246)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(X)

In [74]:
similarity[1]
movie = "Kota Factory"

idx = df[df['title']== movie].index[0]
print(idx)

4

In [75]:
scores = similarity[idx]
print(scores)
scores = list(enumerate(scores))
scores = sorted(scores, key=lambda x: x[1], reverse=True)
scores = scores[1:6]
print(scores)
for i in scores:
    print(df.iloc[i[0]]['title'], i[1])

[0.02396433 0.04155235 0.0692324  ... 0.02888218 0.03741603 0.04206597]
[(8775, np.float64(0.1842624268084065)), (3466, np.float64(0.162526383402356)), (2472, np.float64(0.15505290492812338)), (366, np.float64(0.1477790456706499)), (2353, np.float64(0.146838470478018))]
Yeh Meri Family 0.1842624268084065
Girls Hostel 0.162526383402356
Betaal 0.15505290492812338
Glow Up 0.1477790456706499
Chaman Bahaar 0.146838470478018